# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2749b08495386056d162347cc329e4c51de148c58a99e9064419c6dd54e7378c3109f44fb64cfe9effd91c1e0ce4b749e324083b2c6aa08401ed7c64c1e9a168

test:
  secret_key_base: f05f6dd2199f4b8124363e92e5213f004abf7d71c6ceb23816660dcf3b56bd2b3e00fd5dc11220b38204a293c4fa5152fbfb44c2682e76cb474417cead6b52e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
